# Generated by Django 2.2.12 on 2021-09-25 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letter',
            options={'verbose_name': 'Письмо', 'verbose_name_plural': 'Письма'},
        ),
    ]
